spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework?serverTimezone=GMT%2B8&amp&useSSL=false
    username: root
    password: root

  redis:
    sentinel:
      master:mymaster
      nodes: 47.106.38.101:26379,47.106.38.101:26380
