# DataSource Config
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework?serverTimezone=GMT%2B8&amp&useSSL=false
    username: root
    password: root

  redis:
    #sentinel:
      #master: mymaster
      #nodes: 47.106.38.101:26379,47.106.38.101:26380
    host: 47.106.232.229
    port: 6379
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

server:
  port: 8080