server:
  port: 8761
spring:
  application:
    name: eureka-server-8761
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    register-with-eureka: false